# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: diamonds.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='diamonds.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x64iamonds.proto\"\x1b\n\x0bTypeRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\"\x1c\n\x0cTypeResponse\x12\x0c\n\x04type\x18\x01 \x01(\t\"2\n\x0cRangeRequest\x12\x11\n\tfromRange\x18\x01 \x01(\t\x12\x0f\n\x07toRange\x18\x02 \x01(\t2\xa8\x02\n\x08\x44iamonds\x12\x34\n\x11GetDiamondsByType\x12\x0c.TypeRequest\x1a\r.TypeResponse\"\x00\x30\x01\x12\x35\n\x12GetDiamondsByCarat\x12\x0c.TypeRequest\x1a\r.TypeResponse\"\x00\x30\x01\x12;\n\x17GetDiamondsByCaratRange\x12\r.RangeRequest\x1a\r.TypeResponse\"\x00\x30\x01\x12\x35\n\x12GetDiamondsByColor\x12\x0c.TypeRequest\x1a\r.TypeResponse\"\x00\x30\x01\x12;\n\x17GetDiamondsByPriceRange\x12\r.RangeRequest\x1a\r.TypeResponse\"\x00\x30\x01\x62\x06proto3')
)




_TYPEREQUEST = _descriptor.Descriptor(
  name='TypeRequest',
  full_name='TypeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='TypeRequest.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=45,
)


_TYPERESPONSE = _descriptor.Descriptor(
  name='TypeResponse',
  full_name='TypeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='TypeResponse.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=75,
)


_RANGEREQUEST = _descriptor.Descriptor(
  name='RangeRequest',
  full_name='RangeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fromRange', full_name='RangeRequest.fromRange', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='toRange', full_name='RangeRequest.toRange', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=127,
)

DESCRIPTOR.message_types_by_name['TypeRequest'] = _TYPEREQUEST
DESCRIPTOR.message_types_by_name['TypeResponse'] = _TYPERESPONSE
DESCRIPTOR.message_types_by_name['RangeRequest'] = _RANGEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TypeRequest = _reflection.GeneratedProtocolMessageType('TypeRequest', (_message.Message,), dict(
  DESCRIPTOR = _TYPEREQUEST,
  __module__ = 'diamonds_pb2'
  # @@protoc_insertion_point(class_scope:TypeRequest)
  ))
_sym_db.RegisterMessage(TypeRequest)

TypeResponse = _reflection.GeneratedProtocolMessageType('TypeResponse', (_message.Message,), dict(
  DESCRIPTOR = _TYPERESPONSE,
  __module__ = 'diamonds_pb2'
  # @@protoc_insertion_point(class_scope:TypeResponse)
  ))
_sym_db.RegisterMessage(TypeResponse)

RangeRequest = _reflection.GeneratedProtocolMessageType('RangeRequest', (_message.Message,), dict(
  DESCRIPTOR = _RANGEREQUEST,
  __module__ = 'diamonds_pb2'
  # @@protoc_insertion_point(class_scope:RangeRequest)
  ))
_sym_db.RegisterMessage(RangeRequest)



_DIAMONDS = _descriptor.ServiceDescriptor(
  name='Diamonds',
  full_name='Diamonds',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=130,
  serialized_end=426,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDiamondsByType',
    full_name='Diamonds.GetDiamondsByType',
    index=0,
    containing_service=None,
    input_type=_TYPEREQUEST,
    output_type=_TYPERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDiamondsByCarat',
    full_name='Diamonds.GetDiamondsByCarat',
    index=1,
    containing_service=None,
    input_type=_TYPEREQUEST,
    output_type=_TYPERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDiamondsByCaratRange',
    full_name='Diamonds.GetDiamondsByCaratRange',
    index=2,
    containing_service=None,
    input_type=_RANGEREQUEST,
    output_type=_TYPERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDiamondsByColor',
    full_name='Diamonds.GetDiamondsByColor',
    index=3,
    containing_service=None,
    input_type=_TYPEREQUEST,
    output_type=_TYPERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDiamondsByPriceRange',
    full_name='Diamonds.GetDiamondsByPriceRange',
    index=4,
    containing_service=None,
    input_type=_RANGEREQUEST,
    output_type=_TYPERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DIAMONDS)

DESCRIPTOR.services_by_name['Diamonds'] = _DIAMONDS

# @@protoc_insertion_point(module_scope)
