# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import diamonds_pb2 as diamonds__pb2


class DiamondsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetDiamondsByType = channel.unary_stream(
        '/Diamonds/GetDiamondsByType',
        request_serializer=diamonds__pb2.TypeRequest.SerializeToString,
        response_deserializer=diamonds__pb2.TypeResponse.FromString,
        )
    self.GetDiamondsByCarat = channel.unary_stream(
        '/Diamonds/GetDiamondsByCarat',
        request_serializer=diamonds__pb2.TypeRequest.SerializeToString,
        response_deserializer=diamonds__pb2.TypeResponse.FromString,
        )
    self.GetDiamondsByCaratRange = channel.unary_stream(
        '/Diamonds/GetDiamondsByCaratRange',
        request_serializer=diamonds__pb2.RangeRequest.SerializeToString,
        response_deserializer=diamonds__pb2.TypeResponse.FromString,
        )
    self.GetDiamondsByColor = channel.unary_stream(
        '/Diamonds/GetDiamondsByColor',
        request_serializer=diamonds__pb2.TypeRequest.SerializeToString,
        response_deserializer=diamonds__pb2.TypeResponse.FromString,
        )
    self.GetDiamondsByPriceRange = channel.unary_stream(
        '/Diamonds/GetDiamondsByPriceRange',
        request_serializer=diamonds__pb2.RangeRequest.SerializeToString,
        response_deserializer=diamonds__pb2.TypeResponse.FromString,
        )


class DiamondsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetDiamondsByType(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDiamondsByCarat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDiamondsByCaratRange(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDiamondsByColor(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDiamondsByPriceRange(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DiamondsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetDiamondsByType': grpc.unary_stream_rpc_method_handler(
          servicer.GetDiamondsByType,
          request_deserializer=diamonds__pb2.TypeRequest.FromString,
          response_serializer=diamonds__pb2.TypeResponse.SerializeToString,
      ),
      'GetDiamondsByCarat': grpc.unary_stream_rpc_method_handler(
          servicer.GetDiamondsByCarat,
          request_deserializer=diamonds__pb2.TypeRequest.FromString,
          response_serializer=diamonds__pb2.TypeResponse.SerializeToString,
      ),
      'GetDiamondsByCaratRange': grpc.unary_stream_rpc_method_handler(
          servicer.GetDiamondsByCaratRange,
          request_deserializer=diamonds__pb2.RangeRequest.FromString,
          response_serializer=diamonds__pb2.TypeResponse.SerializeToString,
      ),
      'GetDiamondsByColor': grpc.unary_stream_rpc_method_handler(
          servicer.GetDiamondsByColor,
          request_deserializer=diamonds__pb2.TypeRequest.FromString,
          response_serializer=diamonds__pb2.TypeResponse.SerializeToString,
      ),
      'GetDiamondsByPriceRange': grpc.unary_stream_rpc_method_handler(
          servicer.GetDiamondsByPriceRange,
          request_deserializer=diamonds__pb2.RangeRequest.FromString,
          response_serializer=diamonds__pb2.TypeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Diamonds', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
