# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import message_pb2 as message__pb2


class MessengerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Welcome = channel.unary_unary(
        '/Messenger/Welcome',
        request_serializer=message__pb2.WelcomeRequest.SerializeToString,
        response_deserializer=message__pb2.WelcomeReply.FromString,
        )
    self.AddNumbers = channel.stream_unary(
        '/Messenger/AddNumbers',
        request_serializer=message__pb2.DataRequest.SerializeToString,
        response_deserializer=message__pb2.DataResponse.FromString,
        )
    self.GetPrimes = channel.unary_stream(
        '/Messenger/GetPrimes',
        request_serializer=message__pb2.DataRequest.SerializeToString,
        response_deserializer=message__pb2.DataResponse.FromString,
        )
    self.Chat = channel.stream_stream(
        '/Messenger/Chat',
        request_serializer=message__pb2.InMessage.SerializeToString,
        response_deserializer=message__pb2.OutMessage.FromString,
        )


class MessengerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Welcome(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddNumbers(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPrimes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Chat(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MessengerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Welcome': grpc.unary_unary_rpc_method_handler(
          servicer.Welcome,
          request_deserializer=message__pb2.WelcomeRequest.FromString,
          response_serializer=message__pb2.WelcomeReply.SerializeToString,
      ),
      'AddNumbers': grpc.stream_unary_rpc_method_handler(
          servicer.AddNumbers,
          request_deserializer=message__pb2.DataRequest.FromString,
          response_serializer=message__pb2.DataResponse.SerializeToString,
      ),
      'GetPrimes': grpc.unary_stream_rpc_method_handler(
          servicer.GetPrimes,
          request_deserializer=message__pb2.DataRequest.FromString,
          response_serializer=message__pb2.DataResponse.SerializeToString,
      ),
      'Chat': grpc.stream_stream_rpc_method_handler(
          servicer.Chat,
          request_deserializer=message__pb2.InMessage.FromString,
          response_serializer=message__pb2.OutMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Messenger', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
